version: '2'
services:
  elk:
    build: .
    networks:
      - logging
    ports:
      - "5959:5959"
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"

networks:
  logging:
    driver: bridge
